# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CREDIT.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(80)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(0.254, 0.107955, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(214, 214, 214, 196))
        gradient.setColorAt(1.0, QtGui.QColor(213, 240, 246, 196))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.254, 0.107955, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(214, 214, 214, 196))
        gradient.setColorAt(1.0, QtGui.QColor(213, 240, 246, 196))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.254, 0.107955, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(214, 214, 214, 196))
        gradient.setColorAt(1.0, QtGui.QColor(213, 240, 246, 196))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.254, 0.107955, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(214, 214, 214, 196))
        gradient.setColorAt(1.0, QtGui.QColor(213, 240, 246, 196))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.254, 0.107955, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(214, 214, 214, 196))
        gradient.setColorAt(1.0, QtGui.QColor(213, 240, 246, 196))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.254, 0.107955, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(214, 214, 214, 196))
        gradient.setColorAt(1.0, QtGui.QColor(213, 240, 246, 196))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.254, 0.107955, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(214, 214, 214, 196))
        gradient.setColorAt(1.0, QtGui.QColor(213, 240, 246, 196))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.254, 0.107955, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(214, 214, 214, 196))
        gradient.setColorAt(1.0, QtGui.QColor(213, 240, 246, 196))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.254, 0.107955, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(214, 214, 214, 196))
        gradient.setColorAt(1.0, QtGui.QColor(213, 240, 246, 196))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Bodoni MT Condensed")
        font.setPointSize(16)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("calculator_icon-icons.com_54044.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("calculator_icon-icons.com_54044.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.254, y1:0.107955, x2:1, y2:0, stop:0 rgba(214, 214, 214, 196), stop:1 rgba(213, 240, 246, 196))\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT Condensed")
        font.setPointSize(16)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"  top:-1px; \n"
"} \n"
"\n"
"\n"
"QTabBar::tab {\n"
"  background: rgb(255, 255, 255);\n"
"  border: 2px ridge rgb(214, 216, 217);\n"
"  padding: 15px;\n"
"} \n"
"\n"
"\n"
"\n"
"QTabBar::tab:selected { \n"
"  background: rgb(214, 216, 217);\n"
"  margin-bottom: -1px; \n"
"}")
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(20, 0, 20, 100)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(50)
        self.gridLayout.setObjectName("gridLayout")
        self.begin = QtWidgets.QLabel(self.tab)
        self.begin.setMinimumSize(QtCore.QSize(220, 50))
        self.begin.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT Condensed")
        font.setPointSize(16)
        self.begin.setFont(font)
        self.begin.setStyleSheet("QLabel {\n"
"border: 2px ridge rgb(178, 189, 213);\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.begin.setAlignment(QtCore.Qt.AlignCenter)
        self.begin.setObjectName("begin")
        self.gridLayout.addWidget(self.begin, 3, 0, 1, 1)
        self.percent = QtWidgets.QLabel(self.tab)
        self.percent.setMinimumSize(QtCore.QSize(220, 50))
        self.percent.setMaximumSize(QtCore.QSize(220, 50))
        self.percent.setSizeIncrement(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(16)
        self.percent.setFont(font)
        self.percent.setStyleSheet("QLabel {\n"
"border: 2px ridge rgb(178, 189, 213);\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.percent.setObjectName("percent")
        self.gridLayout.addWidget(self.percent, 6, 0, 1, 1)
        self.type = QtWidgets.QLabel(self.tab)
        self.type.setMinimumSize(QtCore.QSize(220, 50))
        self.type.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT Condensed")
        font.setPointSize(16)
        self.type.setFont(font)
        self.type.setStyleSheet("QLabel {\n"
"border: 2px ridge rgb(178, 189, 213);\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.type.setAlignment(QtCore.Qt.AlignCenter)
        self.type.setObjectName("type")
        self.gridLayout.addWidget(self.type, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.calc = QtWidgets.QPushButton(self.tab)
        self.calc.setMinimumSize(QtCore.QSize(220, 50))
        self.calc.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT Condensed")
        font.setPointSize(16)
        self.calc.setFont(font)
        self.calc.setStyleSheet("QPushButton {\n"
"border: 2px ridge rgb(178, 189, 213);\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #c8d5db\n"
"}\n"
"QPushButton: pressed {\n"
"border: 1px solid #ff0303f4;\n"
"}\n"
"")
        self.calc.setObjectName("calc")
        self.horizontalLayout.addWidget(self.calc)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.choose_time = QtWidgets.QSpinBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_time.sizePolicy().hasHeightForWidth())
        self.choose_time.setSizePolicy(sizePolicy)
        self.choose_time.setMaximum(1000)
        self.choose_time.setMinimumSize(QtCore.QSize(100, 50))
        self.choose_time.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.choose_time.setFont(font)
        self.choose_time.setStyleSheet("QSpinBox {\n"
"border: 2px ridge rgb(178, 189, 213);\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.choose_time.setObjectName("choose_time")
        self.horizontalLayout_3.addWidget(self.choose_time)
        self.month = QtWidgets.QComboBox(self.tab)
        self.month.setMinimumSize(QtCore.QSize(110, 50))
        self.month.setMaximumSize(QtCore.QSize(110, 50))
        self.month.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.month.setFont(font)
        self.month.setStyleSheet("QComboBox {\n"
"border: 2px ridge rgb(178, 189, 213);\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.month.setObjectName("month")
        self.month.addItem("")
        self.month.addItem("")
        self.horizontalLayout_3.addWidget(self.month)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.choose_type = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_type.sizePolicy().hasHeightForWidth())
        self.choose_type.setSizePolicy(sizePolicy)
        self.choose_type.setMinimumSize(QtCore.QSize(210, 50))
        self.choose_type.setMaximumSize(QtCore.QSize(210, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.choose_type.setFont(font)
        self.choose_type.setStyleSheet("QComboBox {\n"
"border: 2px ridge rgb(178, 189, 213);\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.choose_type.setObjectName("choose_type")
        self.choose_type.addItem("")
        self.choose_type.addItem("")
        self.gridLayout.addWidget(self.choose_type, 5, 1, 1, 1)
        self.sum = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sum.sizePolicy().hasHeightForWidth())
        self.sum.setSizePolicy(sizePolicy)
        self.sum.setMinimumSize(QtCore.QSize(220, 50))
        self.sum.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT Condensed")
        font.setPointSize(16)
        self.sum.setFont(font)
        self.sum.setStyleSheet("QLabel {\n"
"border: 2px ridge rgb(178, 189, 213);\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.sum.setAlignment(QtCore.Qt.AlignCenter)
        self.sum.setObjectName("sum")
        self.gridLayout.addWidget(self.sum, 1, 0, 1, 1)
        self.choose_date = QtWidgets.QDateEdit(self.tab)
        self.choose_date.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_date.sizePolicy().hasHeightForWidth())
        self.choose_date.setSizePolicy(sizePolicy)
        self.choose_date.setMinimumSize(QtCore.QSize(150, 50))
        self.choose_date.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.choose_date.setFont(font)
        self.choose_date.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.choose_date.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.choose_date.setAutoFillBackground(False)
        self.choose_date.setStyleSheet("QDateEdit {\n"
"border: 2px ridge rgb(178, 189, 213);\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.choose_date.setAlignment(QtCore.Qt.AlignCenter)
        self.choose_date.setReadOnly(False)
        self.choose_date.setObjectName("choose_date")
        self.gridLayout.addWidget(self.choose_date, 3, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.choose_pct = QtWidgets.QLineEdit(self.tab)
        self.choose_pct.setMinimumSize(QtCore.QSize(110, 50))
        self.choose_pct.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.choose_pct.setFont(font)
        self.choose_pct.setStyleSheet("QLineEdit {\n"
"border: 2px ridge rgb(178, 189, 213);\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.choose_pct.setObjectName("choose_pct")
        self.horizontalLayout_4.addWidget(self.choose_pct)
        self.pct_year = QtWidgets.QComboBox(self.tab)
        self.pct_year.setMinimumSize(QtCore.QSize(100, 50))
        self.pct_year.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pct_year.setFont(font)
        self.pct_year.setStyleSheet("QComboBox {\n"
"border: 2px ridge rgb(178, 189, 213);\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pct_year.setObjectName("pct_year")
        self.pct_year.addItem("")
        self.pct_year.addItem("")
        self.horizontalLayout_4.addWidget(self.pct_year)
        self.gridLayout.addLayout(self.horizontalLayout_4, 6, 1, 1, 1)
        self.time = QtWidgets.QLabel(self.tab)
        self.time.setMinimumSize(QtCore.QSize(220, 50))
        self.time.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT Condensed")
        font.setPointSize(16)
        self.time.setFont(font)
        self.time.setStyleSheet("QLabel {\n"
"border: 2px ridge rgb(178, 189, 213);\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.gridLayout.addWidget(self.time, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.choose_sum = QtWidgets.QLineEdit(self.tab)
        self.choose_sum.setMinimumSize(QtCore.QSize(150, 50))
        self.choose_sum.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.choose_sum.setFont(font)
        self.choose_sum.setStyleSheet("QLineEdit {\n"
"border: 2px ridge rgb(178, 189, 213);\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.choose_sum.setObjectName("choose_sum")
        self.horizontalLayout_2.addWidget(self.choose_sum)
        self.rub = QtWidgets.QLabel(self.tab)
        self.rub.setMinimumSize(QtCore.QSize(60, 50))
        self.rub.setMaximumSize(QtCore.QSize(60, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rub.setFont(font)
        self.rub.setStyleSheet("border: 2px ridge rgb(178, 189, 213);\n"
"border-radius: 7px;\n"
"padding: 5px;\n"
"background-color: rgb(255, 255, 255);")
        self.rub.setAlignment(QtCore.Qt.AlignCenter)
        self.rub.setObjectName("rub")
        self.horizontalLayout_2.addWidget(self.rub)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.output = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output.sizePolicy().hasHeightForWidth())
        self.output.setSizePolicy(sizePolicy)
        self.output.setMinimumSize(QtCore.QSize(268, 288))
        self.output.setMaximumSize(QtCore.QSize(268, 288))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        self.output.setFont(font)
        self.output.setObjectName("output")
        self.gridLayout.addWidget(self.output, 0, 2, 4, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Кредитный калькулятор"))
        self.begin.setText(_translate("MainWindow", "Начало выплат"))
        self.percent.setText(_translate("MainWindow", "Процентная ставка"))
        self.type.setText(_translate("MainWindow", "Тип платежей"))
        self.calc.setText(_translate("MainWindow", "Рассчитать"))
        self.month.setItemText(0, _translate("MainWindow", "месяцев"))
        self.month.setItemText(1, _translate("MainWindow", "лет"))
        self.choose_type.setItemText(0, _translate("MainWindow", "Аннуитетные"))
        self.choose_type.setItemText(1, _translate("MainWindow", "Дифференцированные"))
        self.sum.setText(_translate("MainWindow", "Сумма кредита"))
        self.pct_year.setItemText(0, _translate("MainWindow", "% в год"))
        self.pct_year.setItemText(1, _translate("MainWindow", "% в мес"))
        self.time.setText(_translate("MainWindow", "Срок кредита"))
        self.rub.setText(_translate("MainWindow", "руб."))
        self.output.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Калькулятор"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
